export const usersSeedData = [
  {
    userName: "JuanPerez",
    email: "juanperez@example.com",
    password: "password1!a",
    role: "ADMIN_ROLE",
  },
  {
    userName: "MariaRodriguez",
    email: "mariarodriguez@example.com",
    password: "password2!b",
    role: "PROFESOR_ROLE",
  },
  {
    userName: "CarlosGomez",
    email: "carlosgomez@example.com",
    password: "password3!c",
    role: "PROFESOR_ROLE",
  },
  {
    userName: "LuisaMartinez",
    email: "luisamartinez@example.com",
    password: "password4!d",
    role: "PROFESOR_ROLE",
  },
  {
    userName: "JavierHernandez",
    email: "javierhernandez@example.com",
    password: "password5!e",
    role: "PROFESOR_ROLE",
  },
  {
    userName: "AnaRamirez",
    email: "anaramirez@example.com",
    password: "password6!f",
    role: "PROFESOR_ROLE",
  },
  {
    userName: "PedroCastillo",
    email: "pedrocastillo@example.com",
    password: "password7!g",
    role: "STUDENT_ROLE",
  },
  {
    userName: "SofiaRodriguez",
    email: "sofiarodriguez@example.com",
    password: "password8!h",
    role: "STUDENT_ROLE",
  },
  {
    userName: "MateoPerez",
    email: "mateoperez@example.com",
    password: "password9!i",
    role: "STUDENT_ROLE",
  },
  {
    userName: "ValentinaGomez",
    email: "valentinagomez@example.com",
    password: "password10!j",
    role: "STUDENT_ROLE",
  },
  {
    userName: "ElenaFlores",
    email: "elenaflores@example.com",
    password: "password11!k",
    role: "STUDENT_ROLE",
  },
  {
    userName: "RicardoSanchez",
    email: "ricardosanchez@example.com",
    password: "password12!l",
    role: "STUDENT_ROLE",
  },
  {
    userName: "JulianaTorres",
    email: "julianatorres@example.com",
    password: "password13!m",
    role: "STUDENT_ROLE",
  },
  {
    userName: "GabrielMendoza",
    email: "gabrielmendoza@example.com",
    password: "password14!n",
    role: "STUDENT_ROLE",
  },
  {
    userName: "CarmenSilva",
    email: "carmensilva@example.com",
    password: "password15!o",
    role: "STUDENT_ROLE",
  },
  {
    userName: "FernandoDiaz",
    email: "fernandodiaz@example.com",
    password: "password16!p",
    role: "STUDENT_ROLE",
  },
  {
    userName: "AdrianaVargas",
    email: "adrianavargas@example.com",
    password: "password17!q",
    role: "STUDENT_ROLE",
  },
  {
    userName: "HugoRomero",
    email: "hugoromero@example.com",
    password: "password18!r",
    role: "STUDENT_ROLE",
  },
  {
    userName: "IsabelCastro",
    email: "isabelcastro@example.com",
    password: "password19!s",
    role: "STUDENT_ROLE",
  },
  {
    userName: "AlejandroOrtega",
    email: "alejandroortega@example.com",
    password: "password20!t",
    role: "STUDENT_ROLE",
  },
];
